### ISSUE TITLE
Cannot build a vividus project in a repo if no commit were made

### ISSUE THREAD

**Issue by cherevachy** [vividus-framework/vividus-build-system#13]
Use case: To create a new vividus project the user goes to generator page:  https://github.com/vividus-framework/vividus-starter/generate. The generated project is downloaded from github and placed into a non-github blank repo created for that purpose. Now the user may need to edit the project before producing the initial commit to a repo.
STR:
1. Go to the project folder of a new vividus repo where no commits were made yet
2. run ./gradlew build eclipse (MacOS)
Actual: the build is failed with the following error message:

```
* What went wrong:
A problem occurred evaluating script.
> org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
```

**Comment by valfirst** [comment]
Fixed by #18
